### PR TITLE
Upgrade PHP (->7.1) and phpPgAdmin (->7.12.1)

### PR DESCRIPTION
**Pull request by wapmorgan**
Reinstall some packages and use specific version.

### CODE REVIEW

**Comment by atkrad** [comment]
@wapmorgan Thanks for your contribution.
Sorry for the delayed response. I think we should update the base image to support newer PHP versions so I want to create a new repository (dockage/nginx-php-fpm) and support various os distribution such as Alpine, Debian, Ubuntu, etc and also the new image supports various PHP versions such as 7.1, 7.2, 7.3 and 7.4. if you are agree with me I'll close the pull request.

**Comment by wapmorgan** [comment]
I agree, but how time it will take?

**Comment by atkrad** [comment]
Thank you, utmost one week.

**Comment by GeorgeWL** [comment]
this still seems to be an issue,I'm unable to browse databases at all because of this

**Comment by wapmorgan** [comment]
So, what?

**Comment by wapmorgan** [comment]
@atkrad Any updates?

**Comment by Vaviloff** [comment]
Still is an issue, unfortunately.

**Comment by wapmorgan** [comment]
@atkrad Any updates?

**Comment by wapmorgan** [comment]
Any updates?

**Comment by romw314** [comment]
#6 should fix it for Postgres 16.

**Pull request closed without merging**
